name: Node.js-using Githubaction  CI/CD Pipeline

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest  # or [self-hosted, Prod] if needed
    steps:
      - uses: actions/checkout@v4
      
      # Install Node.js 18
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      # Verify Node + Install/Build
      - run: node -v
      - run: npm install
      - run: npm run build
      
      # Docker Build
      - name: Docker Build
        run: docker build -t nameisvikas/node:1 .
        
      # Trivy Security Scan
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nameisvikas/node:1'
          format: 'table'
          output: 'trivy_report.html'
      
      # Deploy Container
      - name: Run Container
        run: docker run -it -d --name node_container -p 3000:3000 nameisvikas/node:1
        
      - name: Success Message
        run: echo "Pipeline completed successfully!"
